[data]
data_name = "DIV2K+Flickr2K"
train_data_path = "train_dataset"
test_data_path = "test_dataset"

[model]
model_path = "usrnet"

[train]
epochs = 100000
batch_size = 32
learning_rate = 1e-4

[train.wandb]
wandb_name = "usrnet"

[log]
model_save
model_test
