[model]
name = "usrnet"
pretrained_path = ""

[train]
save_snapshots = false
epochs = 100000

lr = 1e-4
n_gpu = [0]
seed = 42
deterministic = false
checkpoint_save = 1000
checkpoint_test = 1000

[train.wandb]
is_enabled = false
project = "usrnet"

[datasets]
batch_size = 32
shuffle = true
num_workers = 4

[datasets.train]
mode = "train"
root_dir = ""


scales = [1, 2, 3, 4]
max_sigma = 25
patch_size = 96

[datasets.test]
mode = "test"
root_dir = ""
scales = [1, 2, 3, 4]
max_sigma = 25
