[model]
name = "defaultnet"
pretrained_path = ""
iter_num = 8

[train]
save_snapshots = false
ls_fn = "l1"
n_gpu = [0]
seed = 42
deterministic = false
checkpoint_save = 1000
checkpoint_test = 1000

[train.optimizer]
name = "adam"
lr = 1e-4
start_factor = 0.1
warmup_epochs = 100
decay_epochs = 1000

[train.wandb]
is_enabled = false
project = "defaultnet"

[datasets]
batch_size = 32
num_workers = 4
pin_memory = false

[datasets.train]
root_dir = "datasets/test/Set14"
patch_size = 96
sf = [1, 2, 3, 4]
sr = [0.2, 0.5]

[datasets.test]
root_dir = "datasets/test/Set5"
