[model]
name = "defaultnet"
pretrained_path = ""
iter_num = 8
init_type = "orthogonal"
init_bn_type = "uniform"
gain = 0.2

[train]
save_snapshots = true
ls_fn = "l1"
n_gpu = [0]
seed = 42
deterministic = false
checkpoint_save = 1000
checkpoint_test = 1000

[train.optimizer]
name = "adam"
lr = 1e-4
start_factor = 0.1
warmup_epochs = 100
decay_epochs = 1000

[train.wandb]
is_enabled = true
project = "defaultnet"

[datasets]
batch_size = 24
num_workers = 0
pin_memory = false

[datasets.train]
root_dir = "/home/test/data/trainH/trainH2"
patch_size = 96
sf = [1, 2, 3, 4]
sr = [0.2, 0.5]

[datasets.val]
root_dir = "/home/test/fuzz/code/USRNext/testsets/imagenet_val_100"

[datasets.test]
root_dir = "datasets/test/Set5"
