[model]
name = "defaultnet"
pretrained_path = ""
iter_num = 8
init_type = "orthogonal"
init_bn_type = "uniform"
gain = 0.2

[train]
save_snapshots = true
ls_fn = "l1"
n_gpu = [0]
seed = 42
deterministic = false
checkpoint_save = 10

[train.optimizer]
name = "adam"
lr = 1e-4
start_factor = 0.1
warmup_epochs = 2
decay_epochs = 1000

[train.wandb]
is_enabled = false
project = "defaultnet"

[datasets]
batch_size = 1
num_workers = 1
pin_memory = false

[datasets.train]
root_dir = "datasets/test/Set14"
patch_size = 192
sf = [1, 2, 3, 4, 8]
sr = [0.2, 0.5]

[datasets.val]
root_dir = "datasets/test/Set14"

[datasets.test]
root_dir = "datasets/test/Set5"
